AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: phial-project

Globals:
  Function:
    Timeout: 5

Resources:
  Runtime:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - provided
      ContentUri: .
    Metadata:
      BuildMethod: makefile

  App:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Datashaman\Phial\Http\Adapter
      Layers:
        - !Ref Runtime
      Runtime: provided
      # ReservedConcurrentExecutions: 10
      # Tracing: Active
      Environment:
        Variables:
          APP_DEBUG: true
          CACHE_DYNAMODB_TABLE: !Ref CacheTable
      Events:
        ProxyApi:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CacheTable
    Metadata:
      BuildMethod: makefile

  CacheTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: key
          AttributeType: S
      KeySchema:
        - AttributeName: key
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: PhialProjectCache
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true

Outputs:
  AppApi:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
